services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  backend:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails db:migrate && bundle exec rails s -b '0.0.0.0'"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      AUTH0_DOMAIN: janus.jp.auth0.com
      AUTH0_JWKS_URI: https://janus.jp.auth0.com/.well-known/jwks.json
    volumes:
      - .:/backend
    ports:
      - "8000:3000"
    restart: always
    tty: true
    stdin_open: true
    depends_on:
      - db

volumes:
  postgres_volume: