default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  password: password
  host: db

development:
  <<: *default
  database: development_postgresql

test:
  <<: *default
  database: test_postgresql

production:
  primary:
    adapter: postgresql
    url: <%= ENV['DATABASE_URL'] %>
  queue:
    adapter: postgresql
    url: <%= ENV['DATABASE_URL'] %>
  cache:
    adapter: postgresql
    url: <%= ENV['DATABASE_URL'] %>
  cable:
    adapter: postgresql
    url: <%= ENV['DATABASE_URL'] %>

