default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  password: password
  host: db

development:
  <<: *default
  database: development_postgresql

test:
  <<: *default
  database: test_postgresql

production:
  primary:
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    url: <%= ENV['HEROKU_POSTGRESQL_MAROON_URL'] %>
    database: production_postgresql
  queue:
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    url: <%= ENV['DATABASE_HEROKU_POSTGRESQL_MAROON_URLURL'] %>
    database: production_postgresql
  cache:
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    url: <%= ENV['HEROKU_POSTGRESQL_MAROON_URL'] %>
    database: production_postgresql

cable:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['HEROKU_POSTGRESQL_MAROON_URL'] %>
  database: production_postgresql

